config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts
  resources :users, only: :show
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, presence:true
  #Postモデルのpostsテーブルでは、imageカラムはnon null 制約をかけます。(createtableのmigrateでも書いたけど。)
  #参考ページ
  # https://qiita.com/wonder_meet/items/fa804f0d436a29c97460
  belongs_to :user
  #postモデルはuserモデル(devise)と1対1関係です。
  # belongs_to :score
  #scoreモデルとの1対1アソシエーションを組むことを断念しました。
  mount_uploader :image, ImageUploader
  #上は、imageカラムの内容(画像)をアップロードするために必要です。(carrierwaveGem)
  def self.returnthisweekposts(allposts)
    this_week = Date.today.all_week
    #this_week = 今日の週です。範囲オブジェクt=>this_week= 2020-03-09..2020-03-15
    # weeklyposts=allposts.where(created_at: this_week).order("posts.created_at DESC")
    weeklyposts=allposts.where(created_at: this_week)
    puts "----allposts.where(created_at: this_week).count= #{weeklyposts}"
    
    # allposts.each do |post| 
    #   puts "---postroop--- allpost.length=#{allposts.length}"
    #   puts post
    #   if (this_week.include?(Date.parse(post[:created_at].to_s)))
    #     puts "--insideif post=#{post}--"
    #     @datas << post
    #   end
    #   # unless (this_week.include?(Date.parse(post[:created_at].to_s)))
    #   #   puts "--insideif post=#{post}--"
    #   #   allposts.delete(post)
    #   # end
    # end
    # puts "---postroop after--- allpost.length=#{allposts.length}"
    # puts "--post.rb @datas--"
    # puts @datas.length
    # puts "@datas[0]=#{@datas[0]}"
    # puts "@datas[0].created_at=#{@datas[0].created_at}"
    puts "allposts.class=#{allposts.class} @weeklyposts.class=#{weeklyposts.class}"
    # binding.pry
    return weeklyposts
    
  end
end
# 今週の日にちの中にpost[:created_at]の年月日が含まれていれば、trueを返す。
        # parseメソッドは、this_weekとpost[:created_at]のclassを合わせるために使用。
        # （this_weekはDateクラス, post[:created_at]はTimeWithZoneクラスのため）

app/controllers/posts_controller.rb
# require 'aws-sdk'
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index,:show]
  #index以外のアクションにはまず、このクラスのmove_to_indexメソッドを通します。
  def index
    @allposts = Post.includes(:user).order("created_at DESC")
    puts "---posts_controller index---"
    puts "@allposts.class = #{@allposts.class}"
    puts "(@allposts)[0].class = #{(@allposts)[0].class}"
    puts "---- #{@allscores = Score.returnscores(@allposts)}"
    @allscores = Score.returnscores(@allposts)
    #全体投稿データから今週の投稿データを作成
    @weeklyposts = Post.returnthisweekposts(@allposts)
    puts "---posts_controller index---"
    puts "@weeklyposts = #{@weeklyposts}"
    puts "@weeklyposts.class = #{@weeklyposts.class}"
    puts "(@weeklyposts)[0].class = #{(@weeklyposts)[0].class}"
    @weeklyscores = Score.returnscores(@weeklyposts)
    # puts "@numberonescore= #{@allscores.order("probabilityup ASC").limit(3)[0].probabilityup}"
    # puts "@numberonescore= #{@allscores.order("probabilityup ASC").limit(3)[0].post_id}"
    @regendscores =@allscores.order("probabilityup ASC").limit(3)
    # binding.pry
  end
  def new
    @post=Post.new
  end
  def create
    @post=Post.new(post_params)
    if (@post.save)
      sleep(15)
      if (@post!=nil)
        filename = @post.image.filename
        filename_ext_removed=filename.split('.')[0]
        Score.createscore(filename_ext_removed,@post.id)
        flash[:notice] = '投稿されました' 
      end
    else
      flash.now[:alert] = '画像は必ず投稿してください。'
      render :new
    end
  end
  def show
    @post = Post.find(params[:id])
    @score=Score.find_by(post_id: @post.id)
    @score_transed=Score.return100score(@score.probabilityup)
  end
  def destroy
    post = Post.find(params[:id])
    score=Score.find_by(post_id: post.id)
    score.destroy
    post.destroy
    flash.now[:notice] = '削除されました' 
    redirect_to root_path
  end
  private
  def post_params
    params.require(:post).permit(:image,:text).merge(user_id: current_user.id)
  end
  def move_to_index
    redirect_to(action: :index) unless user_signed_in?
  end
end

app/views/posts/_form.html.erb
<%= form.file_field :image, class: 'input-box__fileupload formelem'%>
<%= form.text_area :text, class:'formelem',placeholder: :"コメントを記入欄です。空欄でも可です。", rows: "10", id: "text" %>
<%= form.submit '投稿する',class:'formelem'%>

app/views/posts/_post.html.erb
<div class='one_post'>
  <!--<%=image_tag post.image.url,class:'one_post--img'%>-->
  <%= link_to(image_tag(post.image.url,class:'one_post--img'),post_path(post.id))%>
  <div class='one_post__info'>
    <p>点数 : <%=Score.return100score(score.probabilityup)%>点<p>
    <p>投稿日時 : <%=post.created_at.to_s(:datetime_jp)%><p>
    <%= link_to(post.user.nickname,user_path(post.user.id))%>
    <%= link_to('この画像の詳細を表示する',post_path(post.id))%>
  </div>
</div>

app/views/posts/create.html.erb
<h3>投稿が完了しました。<h3>

<%= link_to('Topへもどる',root_path, class: 'btn')%>
<%= link_to('投稿した画像の詳細を表示する',post_path(@post.id), class: 'btn')%>

app/views/posts/index.html.erb
<div class='outer_box'>
  <div class='left_box'>
    <p class='all_box--title'>全ての投稿</p>
    <div class='all_box'>
        <% @allposts.each do |post| %>
          <!---部分テンプレート_post.html.erbを使用します。テンプレート内の変数post:にはeach文のブロックパラメータpostを当てます。-->
          <%= render partial: "post", locals: { post: post,score: @allscores.find_by(post_id: post.id)} %>
        <% end %>
    </div>
  </div>
  <div class='center_box'>
    <p class='weekly_box--title'>今週の投稿</p>
    <div class='weekly_box'>  
        <% @weeklyposts.each do |post| %>
          <!---部分テンプレート_post.html.erbを使用します。テンプレート内の変数post:にはeach文のブロックパラメータpostを当てます。-->
          <%= render partial: "post", locals: { post: post,score: @weeklyscores.find_by(post_id: post.id)} %>
        <% end %>
    </div>
  </div>
  <div class='right_box'>
    <p class='regend_box--title'>点数の上位3つの投稿</p>
    <div class='regendrank_box'>
      <% @regendscores.each do |score| %>
          <!---部分テンプレート_post.html.erbを使用します。テンプレート内の変数post:にはeach文のブロックパラメータpostを当てます。-->
          <%= render partial: "post", locals: { post: @allposts.find_by(id: score.post_id),score: score} %>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="new-outer">
  <div class="formcontainer">
    <%= form_with model: @post, class: :form, local: true do |form| %>
          <h3>投稿する</h3>
          <p>画像はjpg、pngに対応しています。ファイル名に2byte文字を含まないようにしてください。</p>
          <!--以下の部分はedit.html.erbと同じなので_form.html.erbの部分テンプレートにあります。formの入力部分です-->
          <%=render partial: "form", locals: {form: form}%>
          <!--renderの引数はハッシュのキー見たいに考えましょう、partilalキーには文字列、localsキーにはまたハッシュみたいに-->

    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="show-outer">
  <div class="show-post">
    <div class="postDate">
      <p>投稿日時 : <%= @post.created_at.to_s(:datetime_jp) %></p>
    </div>
    <div class="postAuthor">
      <p>投稿者 : <%= @post.user.nickname %></p>
    </div>
    <div class="post_scoretable">
      <p><%=@score.labelup%> である確率 <%=@score.probabilityup%></p>
      <p><%=@score.labeldown%> である確率 <%=@score.probabilitydown%></p>
      <p>点数 : <%=@score_transed%>点</p>
    </div>
    <% if (user_signed_in? && (current_user.id == @post.user_id))  %>
    <div class="postManage">
    <!-- <%= link_to "ç·¨é›†", edit_post_path(@post.id), class: "postManage__edit" %> -->
      <%= link_to "この投稿を削除しますか？", post_path(@post.id), method: :delete%>
    </div>
    <% end %>
    
      <%=image_tag(@post.image.url,class: 'show-post__img')%>
    <p>投稿時のメッセージ</p>
    <div class="show-post__text">
      
      <%= simple_format @post.text %>
      
    </div>
  </div>
</div>